[build]
target = "xtensa-esp32s3-espidf"

[target.'cfg(target_os = "espidf")']
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [ "--cfg",  "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32s3"
ESP_IDF_VERSION = "v5.5.3"
ESP_IDF_TOOLS_INSTALL_DIR = "workspace"
# 搭配 target-dir 必须声明,否则 embuild 找不到工作区根
CARGO_WORKSPACE_DIR = { value = "", relative = true }
ESP_IDF_SDKCONFIG_DEFAULTS = "config/sdkconfig.defaults"
